import { mkdir, readFile, readdir, stat, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import type { AstroIntegration } from "astro";
import sharp from "sharp";

interface LogoAnalysis {
  name: string;
  isWhite: boolean;
  isBlack: boolean;
}

interface LogoCache {
  files: Record<string, number>;
}

const projectRoot = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const srcRoot = join(projectRoot, "src");
const logosDir = join(srcRoot, "logos");
const dataDir = join(srcRoot, "data");
const outputFile = join(dataDir, "white-logos.ts");
const cacheDir = join(projectRoot, ".astro");
const cacheFile = join(cacheDir, "white-logos-cache.json");

async function getLogoSnapshot(): Promise<Record<string, number>> {
  const files = await readdir(logosDir);
  const pngFiles = files.filter((file) => file.endsWith(".png")).sort();
  const entries = await Promise.all(
    pngFiles.map(async (file) => {
      const fileStats = await stat(join(logosDir, file));
      return [file, fileStats.mtimeMs] as const;
    }),
  );

  return Object.fromEntries(entries);
}

async function readCache(): Promise<LogoCache | null> {
  try {
    const contents = await readFile(cacheFile, "utf-8");
    return JSON.parse(contents) as LogoCache;
  } catch {
    return null;
  }
}

async function writeCache(files: Record<string, number>): Promise<void> {
  await mkdir(cacheDir, { recursive: true });
  await writeFile(cacheFile, `${JSON.stringify({ files }, null, 2)}\n`);
}

function snapshotsMatch(
  left: Record<string, number>,
  right: Record<string, number>,
): boolean {
  const leftEntries = Object.entries(left);
  const rightEntries = Object.entries(right);

  if (leftEntries.length !== rightEntries.length) {
    return false;
  }

  return leftEntries.every(([file, mtimeMs]) => right[file] === mtimeMs);
}

async function analyzeLogos(): Promise<LogoAnalysis[]> {
  const files = await readdir(logosDir);
  const pngFiles = files.filter((f) => f.endsWith(".png"));

  const results = await Promise.allSettled(
    pngFiles.map(async (file) => {
      const { data } = await sharp(join(logosDir, file))
        .resize(100, 100, { fit: "inside" })
        .ensureAlpha()
        .raw()
        .toBuffer({ resolveWithObject: true });

      let nonTransparent = 0;
      let whitePixels = 0;
      let blackPixels = 0;
      const whiteThreshold = 240;
      const blackThreshold = 15;

      for (let i = 0; i < data.length; i += 4) {
        if (data[i + 3] < 10) continue;
        nonTransparent++;
        if (
          data[i] >= whiteThreshold &&
          data[i + 1] >= whiteThreshold &&
          data[i + 2] >= whiteThreshold
        ) {
          whitePixels++;
        }
        if (
          data[i] <= blackThreshold &&
          data[i + 1] <= blackThreshold &&
          data[i + 2] <= blackThreshold
        ) {
          blackPixels++;
        }
      }

      return {
        name: file.slice(0, -4),
        isWhite: nonTransparent > 0 && whitePixels / nonTransparent > 0.95,
        isBlack: nonTransparent > 0 && blackPixels / nonTransparent > 0.95,
      };
    }),
  );

  return results
    .filter(
      (r): r is PromiseFulfilledResult<LogoAnalysis> =>
        r.status === "fulfilled",
    )
    .map((r) => r.value);
}

function generateContent(whiteLogos: string[], blackLogos: string[]): string {
  return `// Auto-generated by white-logos integration. Do not edit.
export const whiteLogos = ${JSON.stringify(whiteLogos)} as const;
export const blackLogos = ${JSON.stringify(blackLogos)} as const;
export type WhiteLogo = (typeof whiteLogos)[number];
export type BlackLogo = (typeof blackLogos)[number];
`;
}

async function syncWhiteLogos(
  logger: AstroIntegration["hooks"]["astro:server:setup"] extends (
    ...args: infer T
  ) => any
    ? T[0]["logger"]
    : never,
): Promise<void> {
  const snapshot = await getLogoSnapshot();
  const cache = await readCache();

  if (cache && snapshotsMatch(cache.files, snapshot)) {
    logger.info("Using cached white/black logo analysis");
    return;
  }

  const analyses = await analyzeLogos();
  const whiteLogos = analyses.filter((a) => a.isWhite).map((a) => a.name);
  const blackLogos = analyses.filter((a) => a.isBlack).map((a) => a.name);

  await mkdir(dataDir, { recursive: true });
  await writeFile(outputFile, generateContent(whiteLogos, blackLogos));
  await writeCache(snapshot);

  logger.info(
    `White logos: ${whiteLogos.length > 0 ? whiteLogos.join(", ") : "none"} | Black logos: ${blackLogos.length > 0 ? blackLogos.join(", ") : "none"}`,
  );
}

export function whiteLogosIntegration(): AstroIntegration {
  return {
    name: "white-logos",
    hooks: {
      "astro:build:start": async ({ logger }) => {
        await syncWhiteLogos(logger);
      },
      "astro:server:setup": async ({ logger }) => {
        await syncWhiteLogos(logger);
      },
    },
  };
}
