// Auto-generated by white-logos integration. Do not edit.
export const whiteLogos = ["acmfeup","antennapod","blip","colgaia","feup","purelymail","ua","x"] as const;
export const blackLogos = ["cybersecure","efset","hermes-agent","nextjs","openai","umami","wakatime"] as const;
export type WhiteLogo = (typeof whiteLogos)[number];
export type BlackLogo = (typeof blackLogos)[number];
