// Auto-generated by white-logos integration. Do not edit.
export const whiteLogos = ["acmfeup","blip","colgaia","feup","ua","x"] as const;
export const blackLogos = ["cybersecure","efset","hermes-agent","nextjs","openai","pi","umami","wakatime"] as const;
export type WhiteLogo = (typeof whiteLogos)[number];
export type BlackLogo = (typeof blackLogos)[number];
