// Auto-generated by white-logos integration. Do not edit.
export const whiteLogos = ["acmfeup","colgaia","feup","ua","x"] as const;
export const blackLogos = ["cybersecure","efset","nextjs","openai","openpost","umami","wakatime"] as const;
export type WhiteLogo = (typeof whiteLogos)[number];
export type BlackLogo = (typeof blackLogos)[number];
